### PR TITLE
Replace `v1beta3` in URLs with `v1`

### PR DESCRIPTION
**Pull request by jvoegele**
This fixes error status codes so that we get back a code that indicates the actual error that occurred. Previously, errors would always return error code 3, regardless of the type of error that actually occurred. In our use of Google Datastore in our application, we rely on these error codes to conditionally retry or abort requests, so it is important to us to have correct error codes.

Unfortunately, the `exprotobuf` library cannot parse the new `v1` protobuff files from Google, so the protobuff files were _not_ updated in any way. Only the URLs that are used to make rpc calls were changed.

### CODE REVIEW

**Comment by peburrows** [comment]
So the `v1beta3` protobuf definitions work against the `v1` API endpoints? I've had a branch to update to the `v1` endpoints & protobuf definitions that's been lingering for a while (https://github.com/peburrows/diplomat/compare/v1-api-updates), but if your PR works, that's definitely a step in the right direction.

**Comment by jvoegele** [comment]
The `v1beta3` protobuf definitions do indeed work against the `v1` API endpoints, at least for everything we've tested so far. A full update to `v1` everywhere would be preferable, but at least this gets us the correct error codes that we need.

**Comment by peburrows** [comment]
Awesome, thanks! I'll get this tested out and merged as soon as I get a chance.

**Comment by peburrows** [comment]
Merged and published `v0.6.0` to hex. Thanks again!

**Pull request merged**
